//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urunSatisOto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbUrunSatisEntities : DbContext
    {
        public DbUrunSatisEntities()
            : base("name=DbUrunSatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblMusteriler> TblMusteriler { get; set; }
        public virtual DbSet<TblSatislar> TblSatislar { get; set; }
        public virtual DbSet<TblUrunler> TblUrunler { get; set; }
    
        public virtual ObjectResult<satisListesi_Result> satisListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<satisListesi_Result>("satisListesi");
        }
    
        public virtual ObjectResult<satisListesi2_Result> satisListesi2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<satisListesi2_Result>("satisListesi2");
        }
    }
}
