//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urunSatisOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatislar
    {
        public int satisID { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<int> toplamFiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual TblMusteriler TblMusteriler { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
